function cfg(){const url=process.env.IDLE_KV_REST_API_URL||process.env.IDLE_KV_KV_REST_API_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_URL;const token=process.env.IDLE_KV_REST_API_TOKEN||process.env.IDLE_KV_KV_REST_API_TOKEN||process.env.KV_REST_API_TOKEN||process.env.UPSTASH_REDIS_REST_TOKEN;return url&&token?{url:url.replace(/\/$/,""),token}:null;}
async function cmd(parts){const c=cfg();if(!c)throw new Error("Persistent store not configured");const r=await fetch(c.url,{method:"POST",headers:{Authorization:`Bearer ${c.token}`,"Content-Type":"application/json"},body:JSON.stringify(parts),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error||"Store request failed");return d?.result;}
const gameKey=u=>`idle:test:game:v4:${u}`,boostKey=(u,e)=>`idle:test:boost:${u}:${e}`,payKey=p=>`idle:test:payment:${p}`,rewardKey=(u,e)=>`idle:test:reward:${u}:${e}`,rewardLockKey=(u,e)=>`idle:test:reward-lock:${u}:${e}`,paymentLockKey=p=>`idle:test:payment-lock:${p}`;
const metricsUniqueKey=d=>`idle:test:metrics:unique:${d}`,metricsEventsKey=d=>`idle:test:metrics:events:${d}`,metricsDedupeKey=id=>`idle:test:metrics:dedupe:${id}`;
function configured(){return !!cfg();}
async function claimPayment(uid,id){const x=await cmd(["SET",payKey(id),uid,"NX"]);if(x==="OK")return;const owner=await cmd(["GET",payKey(id)]);if(owner!==uid)throw new Error("Payment already belongs to another account");}
async function acquirePaymentLock(id){const token=`${Date.now()}:${Math.random().toString(36).slice(2)}`;const x=await cmd(["SET",paymentLockKey(id),token,"NX","EX",120]);return x==="OK"?token:null;}
async function releasePaymentLock(id,token){const key=paymentLockKey(id);if((await cmd(["GET",key]))===token)await cmd(["DEL",key]);}
async function hasBoost(uid,era){return configured()&&(await cmd(["GET",boostKey(uid,era)]))==="1";}
async function grantBoost(uid,era,id){await claimPayment(uid,id);await cmd(["SET",boostKey(uid,era),"1"]);}
async function getGame(uid){if(!configured())return null;const raw=await cmd(["GET",gameKey(uid)]);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function saveGame(uid,state){await cmd(["SET",gameKey(uid),JSON.stringify(state)]);return state;}
async function acquireRewardLock(uid,era){const token=`${Date.now()}:${Math.random().toString(36).slice(2)}`;const x=await cmd(["SET",rewardLockKey(uid,era),token,"NX","EX",180]);return x==="OK"?token:null;}
async function releaseRewardLock(uid,era,token){const key=rewardLockKey(uid,era);if((await cmd(["GET",key]))===token)await cmd(["DEL",key]);}
async function setReward(uid,era,value){await cmd(["SET",rewardKey(uid,era),JSON.stringify(value)]);}
async function getReward(uid,era){if(!configured())return null;const raw=await cmd(["GET",rewardKey(uid,era)]);if(!raw)return null;try{return JSON.parse(raw)}catch{return {status:String(raw)}}}
async function recordMetric(day,subject,event,dedupeId=""){const script="if ARGV[3]~='' then local created=redis.call('SET',KEYS[3],'1','NX','EX',ARGV[4]); if not created then return 0 end end; redis.call('PFADD',KEYS[1],ARGV[1]); redis.call('EXPIRE',KEYS[1],ARGV[4]); redis.call('HINCRBY',KEYS[2],ARGV[2],1); redis.call('EXPIRE',KEYS[2],ARGV[4]); return 1";return Number(await cmd(["EVAL",script,"3",metricsUniqueKey(day),metricsEventsKey(day),metricsDedupeKey(dedupeId||"none"),subject,event,dedupeId,"34560000"]))===1}
async function getMetricsReport(days){const count=Math.max(1,Math.min(90,Math.trunc(Number(days)||30))),keys=[],labels=[];for(let offset=0;offset<count;offset++){const date=new Date(Date.now()-offset*86400000).toISOString().slice(0,10);labels.push(date);keys.push(metricsUniqueKey(date),metricsEventsKey(date))}const script="local out={}; for i=1,#KEYS,2 do table.insert(out,{unique=redis.call('PFCOUNT',KEYS[i]),events=redis.call('HGETALL',KEYS[i+1])}) end; return cjson.encode(out)";const rows=JSON.parse(await cmd(["EVAL",script,String(keys.length),...keys]));return labels.map((day,index)=>{const pairs=rows[index]?.events||[],events={};for(let i=0;i<pairs.length;i+=2)events[pairs[i]]=Number(pairs[i+1])||0;return{day,uniqueUsers:Number(rows[index]?.unique)||0,events}})}
module.exports={configured,claimPayment,acquirePaymentLock,releasePaymentLock,hasBoost,grantBoost,getGame,saveGame,acquireRewardLock,releaseRewardLock,setReward,getReward,recordMetric,getMetricsReport};
