function cfg(){const url=process.env.IDLE_KV_REST_API_URL||process.env.KV_REST_API_URL||process.env.UPSTASH_REDIS_REST_URL;const token=process.env.IDLE_KV_REST_API_TOKEN||process.env.KV_REST_API_TOKEN||process.env.UPSTASH_REDIS_REST_TOKEN;return url&&token?{url:url.replace(/\/$/,""),token}:null;}
async function cmd(parts){const c=cfg();if(!c)throw new Error("Persistent store not configured");const r=await fetch(c.url,{method:"POST",headers:{Authorization:`Bearer ${c.token}`,"Content-Type":"application/json"},body:JSON.stringify(parts),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||d?.error)throw new Error(d?.error||"Store request failed");return d?.result;}
const gameKey=u=>`idle:test:game:${u}`,boostKey=(u,e)=>`idle:test:boost:${u}:${e}`,payKey=p=>`idle:test:payment:${p}`,rewardKey=(u,e)=>`idle:test:reward:${u}:${e}`;
function configured(){return !!cfg();}
async function claimPayment(uid,id){const x=await cmd(["SET",payKey(id),uid,"NX"]);if(x==="OK")return;const owner=await cmd(["GET",payKey(id)]);if(owner!==uid)throw new Error("Payment already belongs to another account");}
async function hasBoost(uid,era){return configured()&&(await cmd(["GET",boostKey(uid,era)]))==="1";}
async function grantBoost(uid,era,id){await claimPayment(uid,id);await cmd(["SET",boostKey(uid,era),"1"]);}
async function getGame(uid){if(!configured())return null;const raw=await cmd(["GET",gameKey(uid)]);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function saveGame(uid,state){const safe={v:2,era:["foundations","bronze","iron"].includes(state.era)?state.era:"foundations",pop:Math.max(0,Math.min(1e6,Number(state.pop)||0)),prod:Math.max(0,Math.min(1e9,Number(state.prod)||0)),bronze:Math.max(0,Math.min(1e9,Number(state.bronze)||0)),stab:Math.max(0,Math.min(100,Number(state.stab)||0)),time:Math.max(0,Math.trunc(Number(state.time)||0)),buildings:Array.isArray(state.buildings)?state.buildings.slice(0,18).filter(x=>["⚒️","🏠","🏛️","⛏️","🌾","📚"].includes(x)):[],councilLv:Math.max(0,Math.min(3,Math.trunc(Number(state.councilLv)||0))),sustain:Math.max(0,Math.min(600,Math.trunc(Number(state.sustain)||0))),prestige:Math.max(0,Math.min(1000,Math.trunc(Number(state.prestige)||0))),updatedAt:Date.now()};await cmd(["SET",gameKey(uid),JSON.stringify(safe)]);return safe;}
async function claimReward(uid,era){const key=rewardKey(uid,era);const x=await cmd(["SET",key,"creating","NX"]);return x==="OK";}
async function setReward(uid,era,value){await cmd(["SET",rewardKey(uid,era),value]);}
async function getReward(uid,era){return configured()?await cmd(["GET",rewardKey(uid,era)]):null;}
module.exports={configured,claimPayment,hasBoost,grantBoost,getGame,saveGame,claimReward,setReward,getReward};