const StellarSdk=require("@stellar/stellar-sdk");
const {PI_API_BASE,getServerApiKey,bearer,verifyToken,piPost,getPayment,REWARD_AMOUNT,REWARD_MEMO,validateReward}=require("../lib/pi");
const store=require("../lib/store");
const HORIZON_URL="https://api.testnet.minepi.com";
const NETWORK_PASSPHRASE="Pi Testnet";
const REWARD_ERAS=["foundations","bronze","iron","medieval","renaissance"];
function errorText(value,fallback){if(!value)return fallback;if(typeof value==="string")return value;if(typeof value?.message==="string")return value.message;try{return JSON.stringify(value)}catch{return fallback}}
async function incomplete(){const r=await fetch(`${PI_API_BASE}/payments/incomplete_server_payments`,{headers:{Authorization:`Key ${getServerApiKey()}`},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(errorText(d?.error||d?.message,"Could not inspect incomplete rewards"));return Array.isArray(d?.incomplete_server_payments)?d.incomplete_server_payments:[];}
async function findChainTx(server,address,id){try{const p=await server.transactions().forAccount(address).order("desc").limit(100).call();const x=p.records.find(t=>t.successful&&t.memo_type==="text"&&t.memo===id);return x?.hash||null;}catch{return null;}}
async function submit(p){const seed=process.env.PI_APP_WALLET_SEED;if(!seed)throw new Error("PI_APP_WALLET_SEED not configured");if(!p?.identifier||!p?.to_address)throw new Error("Pi returned an incomplete reward payment");let kp;try{kp=StellarSdk.Keypair.fromSecret(seed)}catch{throw new Error("PI_APP_WALLET_SEED is not a valid Testnet wallet seed")}const server=new StellarSdk.Horizon.Server(HORIZON_URL),source=kp.publicKey();if(p.from_address&&p.from_address!==source)throw new Error("Configured reward wallet does not match this Pi app wallet");const old=await findChainTx(server,source,p.identifier);if(old)return old;await server.loadAccount(p.to_address).catch(()=>{throw new Error("Recipient Pi Testnet wallet is not active on-chain")});const account=await server.loadAccount(source).catch(()=>{throw new Error("Configured app Testnet wallet is not active on-chain")});const tx=new StellarSdk.TransactionBuilder(account,{fee:"1000000",networkPassphrase:NETWORK_PASSPHRASE}).addMemo(StellarSdk.Memo.text(p.identifier)).addOperation(StellarSdk.Operation.payment({destination:p.to_address,asset:StellarSdk.Asset.native(),amount:REWARD_AMOUNT.toFixed(7)})).setTimeout(120).build();tx.sign(kp);try{return (await server.submitTransaction(tx)).hash}catch(e){const code=e?.response?.data?.extras?.result_codes?.transaction||e?.response?.data?.extras?.result_codes?.operations?.join(",")||e?.message;throw new Error(`Pi Testnet transaction failed${code?`: ${code}`:""}`);}}
async function finalize(p,uid,era,recovered=false){const bad=validateReward(p,uid,era);if(bad)throw new Error(bad);const already=await store.getReward(uid,era);if(already?.status==="verified")return already;let txid=p.transaction?.txid||null;if(!p.status?.developer_completed){if(!txid)txid=await submit(p);const c=await piPost(`/payments/${encodeURIComponent(p.identifier)}/complete`,{txid});const completeError=errorText(c.data?.error||c.data?.message,"");if(!c.response.ok&&!completeError.includes("already_completed"))throw new Error(completeError||"Reward completion failed");}p=await getPayment(p.identifier);const bad2=validateReward(p,uid,era);if(bad2)throw new Error(bad2);if(!p.status?.developer_completed||!p.status?.transaction_verified)throw new Error("Reward transaction not fully verified yet");txid=p.transaction?.txid||txid;const receipt={status:"verified",paymentId:p.identifier,txid,amount:REWARD_AMOUNT,recovered,at:Date.now()};await store.setReward(uid,era,receipt);return receipt;}
async function recover(uid,era){const all=await incomplete();const p=all.find(x=>x?.user_uid===uid&&x?.direction==="app_to_user"&&x?.network==="Pi Testnet"&&Number(x?.amount)===REWARD_AMOUNT&&x?.memo===REWARD_MEMO&&x?.metadata?.event==="era_complete"&&x?.metadata?.era===era);return p?finalize(p,uid,era,true):null;}
module.exports=async function(req,res){res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});let lock=null,user=null,era=null;try{const token=bearer(req);if(!token)return res.status(401).json({error:"Missing Pi access token"});user=await verifyToken(token);era=req.body?.era;if(!REWARD_ERAS.includes(era))return res.status(400).json({error:"Invalid reward era"});if(!store.configured())return res.status(503).json({error:"Persistent store unavailable"});if(!process.env.PI_APP_WALLET_SEED)return res.status(503).json({error:"Testnet reward wallet seed is not configured"});const state=await store.getGame(user.uid);if(!state||!Array.isArray(state.completedEras)||!state.completedEras.includes(era))return res.status(403).json({error:"Era reward is not unlocked yet"});const done=await store.getReward(user.uid,era);if(done?.status==="verified")return res.status(200).json({success:true,idempotent:true,...done});lock=await store.acquireRewardLock(user.uid,era);if(!lock)return res.status(409).json({error:"Reward is already being processed",pending:true});const recovered=await recover(user.uid,era);if(recovered)return res.status(200).json({success:true,...recovered});const {response,data}=await piPost("/payments",{payment:{amount:REWARD_AMOUNT,memo:REWARD_MEMO,metadata:{event:"era_complete",era,source:"IdleRealmTest",uid:user.uid},uid:user.uid}});if(!response.ok){const apiError=errorText(data?.error||data?.message,"Reward creation failed");if(apiError.includes("ongoing_payment_found")){const again=await recover(user.uid,era);if(again)return res.status(200).json({success:true,...again});return res.status(409).json({error:"A Test-Pi server payment is still in progress",pending:true});}throw new Error(apiError);}const receipt=await finalize(data,user.uid,era,false);return res.status(200).json({success:true,...receipt});}catch(e){const msg=e?.message||"Reward failed";console.error("Idle Realm A2U reward error",{era,uid:user?.uid||null,message:msg});const status=/Unauthorized|access token/i.test(msg)?401:/not fully verified|still in progress|already being processed/i.test(msg)?409:/not configured|not active|does not match|wallet seed/i.test(msg)?503:500;return res.status(status).json({error:msg,pending:status===409});}finally{if(lock&&user?.uid&&era)await store.releaseRewardLock(user.uid,era,lock).catch(()=>{});}};